### ISSUE TITLE
Tag 0.6.1

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1590]
This issue:
- [x] Bump version number from 0.6 to 0.6.1
    - [x] package.json
    - [x] docs/conf.py
    - [x] style.css
    - [x] readme.md
- [x] run Grunt tasks, see https://github.com/INN/largo/issues/1535 and https://largo.readthedocs.io/developers/grunt-commands.html?highlight=grunt
    - [x] `grunt less`
    - [x] `grunt cssmin`
    - [x] `grunt uglify`
    - [x] `grunt pot`
    - [x] `grunt msmerge`
    - [x] `grunt po2mo`
- [x] Add a changelog https://keepachangelog.com/
- [x] Make sure that migration functions run

Post merge of this branch into 0.5-dev:
- [x] merge 0.5-dev into 0.5

post-release:
- [ ] Release/upgrade docs, blog post
- [ ] bump version number on https://github.com/INN/umbrella-inndev/blob/master/wp-content/themes/largoproject/homepages/templates/largo.php#L6 -> https://github.com/INN/umbrella-inndev/issues/46
- [x] clean up git branches

**Comment by benlk** [comment]
Not able to run `grunt apidocs` at this time; because there's an error of some sort when parsing `functions.php` with the current version of `doxphp`. 

```
$ grunt apidocs
Running "shell:apidocs" (shell) task
Building .rst files
python generate_api_docs.py
PHP Fatal error:  Uncaught TypeError: Argument 2 passed to DoxPHP\Parser\Parser::parseBlock() must be an instance of DoxPHP\Parser\stdClass, instance of stdClass given, called in /Users/blk/.pear/share/pear/DoxPHP/Parser/Parser.php on line 45 and defined in /Users/blk/.pear/share/pear/DoxPHP/Parser/Parser.php:59
Stack trace:
#0 /Users/blk/.pear/share/pear/DoxPHP/Parser/Parser.php(45): DoxPHP\Parser\Parser->parseBlock(Object(DoxPHP\Parser\Tokens), Object(stdClass))
#1 /Users/blk/.pear/bin/doxphp(22): DoxPHP\Parser\Parser->parse(Object(DoxPHP\Parser\Tokens))
#2 {main}
  thrown in /Users/blk/.pear/share/pear/DoxPHP/Parser/Parser.php on line 59
Traceback (most recent call last):
  File "generate_api_docs.py", line 82, in <module>
    process.main()
  File "generate_api_docs.py", line 73, in main
    response = subprocess.check_output(['doxphp < %s' % src], shell=True)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 573, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
subprocess.CalledProcessError: Command '['doxphp < ../functions.php']' returned non-zero exit status 255
make: *** [php] Error 1
```

**Comment by benlk** [comment]
Not able to run `grunt po2mo` at this time:

```
$ grunt po2mo
Running "po2mo:files" (po2mo) task
Warning: Can not create sync-exec directory Use --force to continue.

Aborted due to warnings.
```

I believe that will be taken care of in https://github.com/INN/largo/pull/1560

**Comment by benlk** [comment]
Blog post and https://github.com/INN/largo/issues/1590 are tracked elsewhere; closing this.
