### ISSUE TITLE
Update ReadTheDocs GitHub hook

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1616]
> Hello!
> Your project, Largo, is currently using GitHub Services to trigger builds on Read the Docs. Effective January 31, 2019, GitHub will no longer process requests using the Services feature, and so Read the Docs will not receive notifications on updates to your repository.To continue building your Read the Docs project on changes to your repository, you will need to add a new webhook on your GitHub repository. You can either connect your GitHub account and configure a GitHub webhook integration, or you can add a generic webhook integration.You can find more information on our webhook intergrations in our documentation, at: https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services
> 
> Keep documenting,
> Read the Docs

semirelated: https://github.com/INN/largo/issues/1456

**Comment by benlk** [comment]
Semirelated: https://github.com/INN/largo/issues/1456

**Comment by benlk** [comment]
Followed the instructions at https://docs.readthedocs.io/en/latest/webhooks.html#webhook-integration-github and set up a webhook; it looks like the webhook is communicating successfully.

**Comment by benlk** [comment]
But branch 1616-readthedocs is failing in ReadTheDocs' build stage, and therefore failing to build outright:

```
$ python /home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/bin/sphinx-build -T -E -b readthedocs -d _build/doctrees-readthedocs -D language=en . _build/html

Making output directory...
Running Sphinx v1.2.3
loading translations [en]... done
building [readthedocs]: targets for 66 source files that are out of date
updating environment: 66 added, 0 changed, 0 removed
reading sources... [  1%] api/archive
reading sources... [  3%] api/feed-mailchimp
reading sources... [  4%] api/functions
reading sources... [  6%] api/homepages/homepage
reading sources... [  7%] api/homepages/layouts/HomepageSingleWithSeriesStories
reading sources... [  9%] api/homepages/zones/zones
reading sources... [ 10%] api/inc/ajax-functions
reading sources... [ 12%] api/inc/avatars
reading sources... [ 13%] api/inc/avatars/functions
reading sources... [ 15%] api/inc/byline_class

Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/cmdline.py", line 254, in main
    app.build(force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/application.py", line 220, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 214, in build_update
    'out of date' % len(to_build))
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 234, in build
    purple, length):
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/builders/__init__.py", line 134, in status_iterator
    for item in iterable:
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/environment.py", line 478, in update_generator
    self.read_doc(docname, app=app)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/environment.py", line 628, in read_doc
    pub.publish()
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/core.py", line 217, in publish
    self.settings)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/readers/__init__.py", line 72, in read
    self.parse()
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/readers/__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/__init__.py", line 172, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 170, in run
    input_source=document['source'])
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2726, in underline
    self.section(title, source, style, lineno - 1, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 395, in new_subsection
    node=section_node, match_titles=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/domains/__init__.py", line 190, in run
    return BaseDirective.run(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/directives/__init__.py", line 155, in run
    self.state.nested_parse(self.content, self.content_offset, contentnode)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 282, in nested_parse
    node=node, match_titles=match_titles)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 195, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 239, in run
    context, state, transitions)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/statemachine.py", line 460, in check_line
    return method(match, context, next_state)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2299, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2311, in explicit_construct
    return method(self, expmatch)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2054, in directive
    directive_class, match, type_name, option_presets)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/docutils/parsers/rst/states.py", line 2103, in run_directive
    result = directive_instance.run()
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/domains/__init__.py", line 190, in run
    return BaseDirective.run(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinx/directives/__init__.py", line 136, in run
    name = self.handle_signature(sig, signode)
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinxcontrib/phpdomain.py", line 136, in handle_signature
    if name_prefix.startswith(classname):
TypeError: startswith first arg must be str, unicode, or tuple, not NoneType

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/largo/envs/1616-readthedocs/lib/python2.7/site-packages/sphinxcontrib/phpdomain.py", line 136, in handle_signature
    if name_prefix.startswith(classname):
TypeError: startswith first arg must be str, unicode, or tuple, not NoneType
The full traceback has been saved in /tmp/sphinx-err-5yP8n7.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://bitbucket.org/birkenfeld/sphinx/issues/>. Thanks!
```

**Comment by benlk** [comment]
It builds! https://largo.readthedocs.io/

Currently building off of the 0.5-dev branch.
