### ISSUE TITLE
Highly annoying debug notice in sticky nav

### ISSUE THREAD

**Issue by benlk** [INN/Largo#1623]
Notice: Trying to get property 'has_children' of non-object in /wp-content/themes/largo/inc/nav-menus.php on line 87

If there are a log of items in the sticky nav, this will obscure the entire screen when the sticky nav is visible and WP_DEBUG is true.

Part of #1492.

**Comment by benlk** [comment]
Closed with #1624.

**Comment by benlk** [comment]
> Cannot use object of type stdClass as array in /Users/blk/sites/largo/wp-content/themes/largo/inc/nav-menus.php:87
> Stack trace:
> #0 /Users/blk/sites/largo/wp-content/themes/largo/inc/nav-menus.php(128): Bootstrap_Walker_Nav_Menu->start_el('', Object(WP_Post), 0, Object(stdClass))
> \#1 /Users/blk/sites/largo/wp-includes/class-wp-walker.php(243): Bootstrap_Walker_Nav_Menu->display_element(Object(WP_Post), Array, 0, 0, Array, '')
> \#2 /Users/blk/sites/largo/wp-includes/nav-menu-template.php(531): Walker->walk(Array, 0, Object(stdClass))
> \#3 /Users/blk/sites/largo/wp-includes/nav-menu-template.php(191): walk_nav_menu_tree(Array, 0, Object(stdClass))
> \#4 /Users/blk/sites/largo/wp-content/themes/largo/inc/nav-menus.php(180): wp_nav_menu(Object(stdClass))
> \#5 /Users/blk/sites/largo/wp-content/themes/largo/partials/nav-sticky.php(138): largo_nav_menu(Array)
> \#6 /Users/blk/sites/largo/wp-includes/template.php(690): require('/Users/blk/site...')
> \#7 /Users/blk/sites/largo/wp-inc" while reading upstream, client: 127.0.0.1, server: largo.test, request: "GET / HTTP/2.0", upstream: "fastcgi://unix:/Users/blk/.config/valet/valet.sock:", host: "largo.test"

**Comment by benlk** [comment]
Closed with #1625, again, but let's keep awareness of this issue in case it reappears.
