### ISSUE TITLE
Post-social.php syntax error

### ISSUE THREAD

**Issue by rlambertsen** [INN/Largo#1884]
Using Wordpress 5.7
PHP 8.0.3
Largo 0.6.4

When I installed the theme for doc rewrite I came across this issue.

Opening any post would throw this error

`Fatal error: Uncaught ValueError: Unknown format specifier "D" in /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/inc/post-social.php:113 Stack trace: #0 /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/inc/post-social.php(113): sprintf('<span data-serv...', 'Email', 'bob%20the%20bui...', 'hey%20im%20bob%...', 'https%3A%2F%2Fl...') #1 /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/partials/content-single.php(22): largo_post_social_links() #2 /Users/rylan/Desktop/sites/largo/wp-includes/template.php(732): require('/Users/rylan/De...') #3 /Users/rylan/Desktop/sites/largo/wp-includes/template.php(676): load_template('/Users/rylan/De...', false, Array) #4 /Users/rylan/Desktop/sites/largo/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #5 /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/single-one-column.php(26): get_template_part('partials/conten...', 'single') #6 /Users/rylan/Desktop/sites/largo/wp-includes/template.php(732): require('/Users/rylan/De...') #7 /Users/rylan/Desktop/sites/largo/wp-includes/template.php(676): load_template('/Users/rylan/De...', false, Array) #8 /Users/rylan/Desktop/sites/largo/wp-includes/general-template.php(204): locate_template(Array, true, false, Array) #9 /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/single.php(8): get_template_part('single-one-colu...') #10 /Users/rylan/Desktop/sites/largo/wp-includes/template-loader.php(106): include('/Users/rylan/De...') #11 /Users/rylan/Desktop/sites/largo/wp-blog-header.php(19): require_once('/Users/rylan/De...') #12 /Users/rylan/Desktop/sites/largo/index.php(17): require('/Users/rylan/De...') #13 /Users/rylan/.composer/vendor/laravel/valet/server.php(219): require('/Users/rylan/De...') #14 {main} thrown in /Users/rylan/Desktop/sites/largo/wp-content/themes/largo/inc/post-social.php on line 113`

This looks to come from the social share buttons.

https://github.com/WPBuddy/largo/blob/fb6580686f90cce530acaa385be2a8cc02736b56/inc/post-social.php#L108-L114

**Comment by rlambertsen** [comment]
closing as this PR fixes this issue https://github.com/WPBuddy/largo/pull/1886
